### ISSUE TITLE
feat: use Tabs, not Spaces

### ISSUE THREAD

**Issue by ManuelFeller** [Boehringer-Ingelheim/prettier-config#1]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/boehringer-ingelheim/prettier-config/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to see tabs as indentation method, not a fixed number of spaces.

### Describe the Use Case

To be able to choose my preferred default indentation width without conflicting with the preference of any colleague I suggest to use tabs by default and allow each team(-member) to have their own indentation width settings in their editor / IDE.

While this may or may not have a11y implications (see https://adamtuttle.codes/blog/2021/tabs-vs-spaces-its-an-accessibility-issue/) it is mainly to not force a personal preference onto others and give the possibility to choose.

### Describe Preferred Solution

Let prettier aways use tabs for indentation in our shared configuration by default by adding `useTabs: true` to it

### Describe Alternatives

- forcing everyone with a different preference / settings to use hooks on checkout and commit that do the formatting change
- manually changing the indentation with your editor / IDE on edit and remove it on commit with prettier

### Additional Information

The new version would then look like this:

```javascript
module.exports = {
  printWidth: 120,
  useTabs: true,
};
```

**Comment by SimonGolms** [comment]
Thanks @ManuelFeller for opening this feature request and raising awareness of this issue, which we highly appreciate it!
@Boehringer-Ingelheim/web-code-configurations have spent some time internally on this and also looked at the discussion in prettier repository that has been going on for a few years now (see: https://github.com/prettier/prettier/issues/7475). We have also started to working with `tabs` in our projects and encountered first incompatibilities with `tabs` for example in `yaml` files, which by specification have to be indented with `spaces` (see: https://yaml.org/spec/1.2.2/index.html#61-indentation-spaces).

This has led us to not being able to estimate what incompatibilities it may lead to with other files and processes. Before we start to maintain all exceptions in our repository, we would prefer to stay as close as possible to the default values and leave this topic/discussion to prettier itself.

However and if needed, the `prettier-config` can be easily customized. The decision whether to use `tabs` or `spaces` would therefore be passed to the project/team/person itself.

**Comment by nickserv** [comment]
All these issues are solved by simply using Prettier. For example, enabling `useTabs` in Prettier will still add spaces to your Yaml files (based on `tabWidth` as usual). I'd strongly encourage you to reconsider this for accessibility, as compatibility is not an issue.
